services:
  nxtgenhub-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nxtgenhub-client
    ports:
      - "${APP_PORT}:3000"
    environment:
      - VITE_BACKEND_URL=http://nxtgenhub-server:3001
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nxtgenhub-network

  nxtgenhub-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nxtgenhub-server
    ports:
      - "${SERVER_PORT}:3001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nxtgenhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    container_name: nxtgenhub-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - nxtgenhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  nxtgenhub-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  nxtgenhub-logs:
    driver: local
  pgdata:
